[metadata]
name = vulscan
version = 0.1.0
description = Advanced port, service, and vulnerability scanner with CVE lookup and OSINT integration.
long_description = file: README.md
long_description_content_type = text/markdown
author = Gringobin
license = MIT
license_files = license/LICENSE
url = https://github.com/gringobin/Vulscan-
keywords = security, pentest, vulnerability, scanner, OSINT, CVE

classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
include_package_data = True

install_requires =
    python-nmap
    requests
    colorama
    tabulate

[options.entry_points]
console_scripts =
    vulscan = vulscan.main:main

[options.package_data]
* = *.txt, *.md